Add getCopyData helper functions to consume all rows
haskellari/postgresql-simple pull request #56
Opened 2020-11-23 02:45 UTC by sestrella

This PR introduces two new functions built on top of getCopyData:
- withCopyData: Navigates over all copied rows one at a time sending each row to a consumer function, and returning the number of rows copied.
- getAllCopyData: Get all rows and the number of rows copied as a tuple.

2020-11-24 20:49 UTC, phadej requested changes
The `withCopyData` and `getAllCopyData` are too specific functions.

I'd rather write something like

```haskell
-- | Fold over @COPY TO STDOUT@ query. ... same notes as for 'getCopyData'.
foldCopyData
    :: (a -> ByteString -> IO a)  -- ^ Accumulate one row of the result
    -> (a -> Int64 -> IO b)       -- ^ Post-process accumulator with a count of rows
    -> a                          -- ^ Initial accumulator
    -> IO b                       -- ^ Result
```

and let people specialise.

Your `getAllCopyData` has performance issue, `++` is quadratic when used like that.
Check difference lists (i.e. composing `[a] -> [a]` functions).
It would be a simple instantiation of `foldCopyData`

2020-11-24 21:52 UTC, sestrella commented
@phadej thank you for the feedback! I completely agree with you, I think both functions could be replaced by a more general function.

2020-11-25 08:33 UTC, phadej reviewed
Looks better!

2020-11-25 08:33 UTC, phadej commented on src/Database/PostgreSQL/Simple/Copy.hs
> +foldCopyData conn f g acc = do
Make `acc` strict, i.e. `foldCopyData conn f g !acc = ...`

2020-11-25 08:33 UTC, phadej commented on src/Database/PostgreSQL/Simple/Copy.hs
> +      CopyOutRow row    -> f acc row >>= foldCopyData conn f g
4 spaces

2020-11-25 15:07 UTC, sestrella commented on src/Database/PostgreSQL/Simple/Copy.hs
> +foldCopyData conn f g acc = do
Done, I just made `acc` strict

2020-11-25 15:09 UTC, sestrella commented on src/Database/PostgreSQL/Simple/Copy.hs
> +      CopyOutRow row    -> f acc row >>= foldCopyData conn f g
My bad, I thought I covered all styling issues. I added some extra space.

2020-11-25 15:58 UTC, merged

2020-11-25 15:58 UTC, phadej commented
Good, thanks!

2021-01-06 18:51 UTC, phadej commented
Released in [`postgresql-0.6.4`](https://hackage.haskell.org/package/postgresql-simple-0.6.4)